
- name: Installation von OMNeT++ 6.1 und INET 4
  hosts: localhost
  become: true
  vars:
    omnetpp_version: "6.1"
    omnetpp_url: "https://github.com/omnetpp/omnetpp/releases/download/omnetpp-6.1.0/omnetpp-6.1.0-linux-x86_64.tgz"
    inet_version: "4.5.4"
    inet_url: "https://github.com/inet-framework/inet/releases/download/v4.5.4/inet-4.5.4-src.tgz"
    install_dir: "/opt/omnetpp-{{ omnetpp_version }}"

  tasks:
    - name: Installiere erforderliche Pakete
      apt:
        name:
          - build-essential
          - gcc
          - g++
          - bison
          - flex
          - perl
          - tcl-dev
          - tk-dev
          - libxml2-dev
          - zlib1g-dev
          - default-jre
          - default-jdk
          - libwebkit2gtk-4.0-37
          - git
          - wget
          - unzip
        state: present
        update_cache: yes

    - name: Lade OMNeT++ herunter
      get_url:
        url: "{{ omnetpp_url }}"
        dest: "/tmp/omnetpp-{{ omnetpp_version }}.tgz"

    - name: Entpacke OMNeT++
      unarchive:
        src: "/tmp/omnetpp-{{ omnetpp_version }}.tgz"
        dest: "/opt/"
        remote_src: yes

    - name: Führe das Installationsskript von OMNeT++ aus
      command: "./install.sh -y"
      args:
        chdir: "{{ install_dir }}"

    - name: Setze Umgebungsvariablen für OMNeT++
      shell: source setenv 
      args:
        chdir: "{{ install_dir }}"
        executable: /bin/bash
