- name: Xfce customizations
  hosts: localhost
  vars:
  tasks:
    - name: Set active xfce theme
      xfconf:
        channel: "xsettings"
        property: "/Net/ThemeName"
        value_type: "string"
        value: "PRO-dark-XFCE-4.14"
    - name: Download background TODO Checksum
      get_url:
        url: https://w.wallhaven.cc/full/d6/wallhaven-d6m3gl.png
        dest: ./wallpaper-scimbe.png
        mode: 0644
    - name: Change wallpaper
      xfconf:
        channel: xfce4-desktop
        property: "/backdrop/screen0/{{item}}/workspace0/last-image"
        value_type: string
        value: ["{{ lookup('ansible.builtin.env', 'PWD') }}/playbooks/ubuntu/xfc4/wallpaper-scimbe.png"]
      loop:
        - VNC-0
        - monitorVNC-0
        - VNC-1
        - monitor0
        - monitor1
        - monitorDP-1
        - monitoreDP-0
    - name: Clone a github repository
     git:
       repo: https://github.com/yeyushengfan258/Reversal-icon-theme 
       dest: ~/Reversal-icon-theme
       clone: yes
       update: yes
   - name: Install Icon Theme
     ansible.builtin.script: ~/Reversal-icon-theme/install.sh
     args:
       executable: /bin/bash
       
