- name: Xfce customizations
  hosts: localhost
  become: true
  tasks:
    - name: Download background TODO Checksum
      become_user: abc
      get_url:
        url: https://scimbe.de/wall/wallpaper-big.png
        dest: /config/wallpaper-scimbe.png
        mode: 0666
        
    - name: Conky
      become_user: abc
      get_url:
        url: https://scimbe.de/script/conky
        dest: /config/.conkyrc
        mode: 0666
        
    - name: Disable Removable Devices on Desktop
      become_user: abc
      xfconf:
        channel: xfce4-desktop
        property: "/desktop-icons/file-icons/show-removable"
        value_type: bool
        value: "false"


    - name: disable filesystem
      become_user: abc
      xfconf:
        channel: xfce4-desktop
        property: "/desktop-icons/file-icons/show-filesystem"
        value_type: bool
        value: "false"
        
    - name: disable home
      become_user: abc
      xfconf:
        channel: xfce4-desktop
        property: "/desktop-icons/file-icons/show-home"
        value_type: bool
        value: "false"
        
    - name: Ausführung von 'conky' im Hintergrund
      become_user: abc
      ansible.builtin.shell: |
        nohup conky > /dev/null 2>&1 &
      args:
        chdir: "/"
        

    - name: Change wallpaper
      become_user: abc
      xfconf:
        channel: xfce4-desktop
        property: "/backdrop/screen0/monitorVNC-0/workspace{{item}}/last-image"
        value_type: string
        value: "/config/wallpaper-scimbe.png"
      loop:
        - 0
        - 1
        - 2
        - 3

    - name: Clone a github repository for theme
      become_user: abc
      git:
        repo: https://github.com/paullinuxthemer/PRO-Dark-XFCE-Edition/ 
        dest: ~/.themes
        clone: yes
        update: yes

    - name: Set active xfce theme
      become_user: abc
      xfconf:
        channel: xsettings
        property: "/Net/ThemeName"
        value_type: string
        value: "PRO-dark-XFCE-4.14"
        
    - name: Setzen des Passworts für Benutzer 'abc'
      ansible.builtin.user:
        name: abc
        password: "{{ 'mininet' | password_hash('sha512') }}"
        
   
