- name: Xfce customizations
  hosts: localhost
  become: true
  vars:
    desktop_user: mininet
    wallpaper:
      url: https://scimbe.de/wall/wallpaper-big.png
      path: /headless/wallpaper-scimbe.png
    conky:
      url: https://scimbe.de/script/conky
      path: /headless/.conkyrc
    theme:
      repo: https://github.com/paullinuxthemer/PRO-Dark-XFCE-Edition/
      name: PRO-dark-XFCE-4.14

  tasks:
    - name: Install required packages
      apt:
        name: 
          - nano
          - net-tools
          - conky-all
        state: latest
        update_cache: true

    - name: Configure desktop environment
      become_user: "{{ desktop_user }}"
      environment:
        DISPLAY: ":1"
        XAUTHORITY: "/home/{{ desktop_user }}/.Xauthority"
      block:
        - name: Download background
          get_url:
            url: "{{ wallpaper.url }}"
            dest: "{{ wallpaper.path }}"
            mode: '0666'

        - name: Download Conky configuration
          get_url:
            url: "{{ conky.url }}"
            dest: "{{ conky.path }}"
            mode: '0666'

        - name: Configure desktop icons
          xfconf:
            channel: xfce4-desktop
            property: "/desktop-icons/file-icons/show-{{ item }}"
            value_type: bool
            value: "false"
          loop:
            - removable
            - filesystem
            - home

        - name: Get active monitor name
          shell: xrandr --listmonitors | grep -v "Monitors" | awk '{print $NF}' | head -n1
          register: active_monitor
          changed_when: false

        - name: Set wallpaper for all workspaces
          block:
            - name: Get all available monitors
              shell: xfconf-query -c xfce4-desktop -l | grep monitor
              register: available_monitors
              changed_when: false
        
            - name: Set wallpaper for each monitor and workspace
              xfconf:
                channel: xfce4-desktop
                property: "/backdrop/screen0/{{ item.0 }}/workspace{{ item.1 }}/last-image"
                value_type: string
                value: "{{ wallpaper.path }}"
              with_nested:
                - "{{ available_monitors.stdout_lines }}"
                - [0, 1, 2, 3]
              ignore_errors: true

        - name: Force desktop reload
          shell: |
            xfdesktop --quit || true
            sleep 2
            xfdesktop &
          async: 300
          poll: 0

        - name: Start Conky
          shell: nohup conky > /dev/null 2>&1 &
          args:
            chdir: "/"

        - name: Setup theme
          block:
            - name: Clone theme repository
              git:
                repo: "{{ theme.repo }}"
                dest: /headless/.themes
                clone: yes
                update: yes

            - name: Apply theme
              xfconf:
                channel: xsettings
                property: "/Net/ThemeName"
                value_type: string
                value: "{{ theme.name }}"
