- name: Xfce customizations
  hosts: localhost
  become_user: abc
  tasks:
    - name: Warte auf den xfconfd-Dienst
      ansible.builtin.command: pgrep -a xfconfd
      register: pgrep_result
      until: pgrep_result.stdout != ""
      retries: 10
      delay: 5
      ignore_errors: yes

    - name: Download background TODO Checksum
      get_url:
        url: https://scimbe.de/wall/wallpaper-big.png
        dest: ~/wallpaper-scimbe.png
        mode: 0666
    - name: Conky
      get_url:
        url: https://scimbe.de/script/conky
        dest: ~/.conkyrc
        mode: 0666
    - name: Disable Removable Devices on Desktop
      xfconf:
        channel: xfce4-desktop
        property: "/desktop-icons/file-icons/show-removable"
        value_type: bool
        value: "false"


    - name: disable filesystem
      xfconf:
        channel: xfce4-desktop
        property: "/desktop-icons/file-icons/show-filesystem"
        value_type: bool
        value: "false"
        
    - name: disable home
      xfconf:
        channel: xfce4-desktop
        property: "/desktop-icons/file-icons/show-home"
        value_type: bool
        value: "false"
        
    - name: Ausführung von 'conky' im Hintergrund
      ansible.builtin.shell: |
        nohup conky > /dev/null 2>&1 &
      become_user: abc
      args:
        chdir: "/"
    - name: Setzen des Passworts für Benutzer 'abc'
      ansible.builtin.user:
        name: abc
        password: "{{ 'mininet' | password_hash('sha512') }}"
        
    - name: Change wallpaper
      xfconf:
        channel: xfce4-desktop
        property: "/backdrop/screen0/{{item}}/workspace0/last-image"
        value_type: string
        value: "~/wallpaper-scimbe.png"
      loop:
        - VNC-0
        - monitorVNC-0
        - VNC-1
        - monitor0
        - monitor1
        - monitorDP-1
        - monitoreDP-0

    - name: Clone a github repository for theme
      git:
        repo: https://github.com/paullinuxthemer/PRO-Dark-XFCE-Edition/ 
        dest: ~/.themes
        clone: yes
        update: yes

    - name: Set active xfce theme
      xfconf:
        channel: xsettings
        property: "/Net/ThemeName"
        value_type: string
        value: "PRO-dark-XFCE-4.14"

    - name: Clone a github repository for icons
      git:
        repo: https://github.com/yeyushengfan258/Reversal-icon-theme 
        dest: ~/Reversal-icon-theme
        clone: yes
        update: yes

    - name: Creates directory
      ansible.builtin.file:
        path: /config/.icons
        state: directory
        mode: '0755'

    - name: Install Icon Theme
      command: chdir=~/Reversal-icon-theme /bin/bash install.sh -d ~/.icons
      
    - name: Change icon Theme Reversal-dark
      xfconf:
        channel: xfce4-desktop
        property: "/Net/IconThemeName"
        value_type: string
        value: "Reversal-dark"

   
