- name: Xfce customizations
  hosts: localhost
  become: true
  vars:
    desktop_user: mininet
    wallpaper:
      url: https://scimbe.de/wall/wallpaper-big.png
      path: /headless/wallpaper-scimbe.png
    conky:
      url: https://scimbe.de/script/conky
      path: /headless/.conkyrc
    theme:
      repo: https://github.com/paullinuxthemer/PRO-Dark-XFCE-Edition/
      name: PRO-dark-XFCE-4.14

  tasks:
    - name: Install yad
      apt:
        name: yad
        state: present
    - name: Start persistent notification
      become_user: "{{ desktop_user }}"
      environment:
        DISPLAY: ":1"
        DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/1000/bus"
      shell: |
        yad --notification \
          --text="Ansible configuration in progress..." \
          --image=system-run \
          --command="echo 'Running'" &
        echo $! > /tmp/notify.pid
      async: 300
      poll: 0
      
    - name: Install required packages
      apt:
        name: 
          - nano
          - net-tools
          - conky-all
        state: latest
        update_cache: true

    - name: Ensure XFCE4 is running
      become_user: "{{ desktop_user }}"
      environment:
        DISPLAY: ":1"
        XAUTHORITY: "/home/{{ desktop_user }}/.Xauthority"
      shell: |
        pgrep xfce4-session || xfce4-session &
      async: 300
      poll: 0

    - name: Wait for XFCE4 to start
      wait_for:
        timeout: 10

    - name: Configure desktop environment
      become_user: "{{ desktop_user }}"
      environment:
        DISPLAY: ":1"
        XAUTHORITY: "/home/{{ desktop_user }}/.Xauthority"
      block:
        - name: Download background
          get_url:
            url: "{{ wallpaper.url }}"
            dest: "{{ wallpaper.path }}"
            mode: '0666'

        - name: Download Conky configuration
          get_url:
            url: "{{ conky.url }}"
            dest: "{{ conky.path }}"
            mode: '0666'

        - name: Configure desktop icons
          xfconf:
            channel: xfce4-desktop
            property: "/desktop-icons/file-icons/show-{{ item }}"
            value_type: bool
            value: "false"
          loop:
            - removable
            - filesystem
            - home

        - name: Disable all desktop icons
          xfconf:
            channel: xfce4-desktop
            property: "/desktop-icons/style"
            value_type: int
            value: 0
            
        - name: Set wallpaper directly
          shell: |
            xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorVNC-0/workspace0/last-image -s "{{ wallpaper.path }}"
            xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorVNC-0/workspace1/last-image -s "{{ wallpaper.path }}"
            xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorVNC-0/workspace2/last-image -s "{{ wallpaper.path }}"
            xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorVNC-0/workspace3/last-image -s "{{ wallpaper.path }}"

        - name: Kill existing xfdesktop process
          shell: killall xfdesktop || true
          ignore_errors: yes

        - name: Wait for process to end
          wait_for:
            timeout: 2

        - name: Start xfdesktop
          shell: xfdesktop &
          async: 300
          poll: 0

        - name: Start Conky
          shell: killall conky || true; nohup conky > /dev/null 2>&1 &
          args:
            chdir: "/"

        - name: Setup theme
          block:
            - name: Clone theme repository
              git:
                repo: "{{ theme.repo }}"
                dest: /headless/.themes
                clone: yes
                update: yes

            - name: Apply theme
              xfconf:
                channel: xsettings
                property: "/Net/ThemeName"
                value_type: string
                value: "{{ theme.name }}"

                value: "{{ theme.name }}"

    - name: Remove persistent notification
      become_user: "{{ desktop_user }}"
      shell: "kill $(cat /tmp/notify.pid) || true"
