- name: Create Setup for webtop
  hosts: all
  become: yes
  vars:
    test_url: "http://www.example.com"

  tasks:
    - name: Überprüfung der Internetverbindung
      ansible.builtin.uri:
        url: "{{ test_url }}"
        method: GET
      register: internet_check
      until: internet_check is succeeded
      retries: 1000
      delay: 5

    - name: Aktualisierung der Paketlisten, falls notwendig
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # Der Cache wird nur aktualisiert, wenn er älter als 1 Stunde ist

    - name: Installation erforderlicher Pakete
      ansible.builtin.apt:
        name:
          - ca-certificates
          - ansible
          - openssh-server
          - xpra
          - python3-gi-cairo
          - wget
          - sshpass
          - conky
        state: present

    - name: Start des SSH-Services
      ansible.builtin.service:
        name: ssh
        state: started

    - name: Ausführung von 'conky' im Hintergrund
      ansible.builtin.shell: |
        nohup ./connect-to-mininet.sh > /dev/null 2>&1 &
      become: yes
      become_user: abc
      args:
        chdir: "/"

    - name: Setzen des Passworts für Benutzer 'abc'
      ansible.builtin.user:
        name: abc
        password: "{{ 'mininet' | password_hash('sha512') }}"

    - name: Festlegen von Umgebungsvariablen
      ansible.builtin.set_fact:
        CADS_COMPLETE: true
      when: internet_check is succeeded
