- name: Create Setup for webtop
  hosts: all
  become: yes
  vars:
    test_url: "http://www.example.com"
    url: "https://scimbe.de/script/install-xubuntu.sh"
    target_file: "/config/install-xubuntu.sh"

  tasks:
    - name: Überprüfung der Internetverbindung
      ansible.builtin.uri:
        url: "{{ test_url }}"
        method: GET
      register: internet_check
      until: internet_check is succeeded
      retries: 1000
      delay: 5

    - block:
        - name: Download des Installationsskripts
          ansible.builtin.get_url:
            url: "{{ url }}"
            dest: "{{ target_file }}"
            mode: '0777'
          register: download_result
          until: download_result is succeeded
          retries: 5
          delay: 1

    - name: Aktualisierung der Paketlisten, falls notwendig
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # Der Cache wird nur aktualisiert, wenn er älter als 1 Stunde ist

    - name: Installation erforderlicher Pakete
      ansible.builtin.apt:
        name:
          - ca-certificates
          - ansible
          - openssh-server
          - xpra
          - python3-gi-cairo
          - wget
          - sshpass
          - conky
        state: present

    - name: Ausführung von 'install-xubuntu.sh'
      ansible.builtin.shell: |
        cd /config
        nohup ./install-xubuntu.sh &
      become: yes
      become_user: abc
      args:
        chdir: "/"

    - name: Start des SSH-Services
      ansible.builtin.service:
        name: ssh
        state: started

    - name: Ausführung von 'connect-to-mininet.sh' und 'conky' im Hintergrund
      ansible.builtin.shell: |
        nohup conky > /dev/null 2>&1 &
        nohup ./connect-to-mininet.sh > /dev/null 2>&1 &
      become: yes
      become_user: abc
      args:
        chdir: "/"

    - name: Setzen des Passworts für Benutzer 'abc'
      ansible.builtin.user:
        name: abc
        password: "{{ 'mininet' | password_hash('sha512') }}"

    - name: Festlegen von Umgebungsvariablen
      ansible.builtin.set_fact:
        CADS_COMPLETE: true
      when: internet_check is succeeded
