- hosts: all
  become: yes
  tasks:
  - name : Install packages in loop
    apt: name={{item}} state=latest update_cache=true
  - name : Install   loop:
        - nano
        - net-tools
        = wireshark
