- hosts: all
  vars:
    my_pkgs:
      - sublime-text
      - google-chrome-stable

tasks:
  - name: Install GPG key for SubLimeText
    apt_key:
      url: https://download.sublimetext.com/sublimehq-pub.gpg
      state: present

  - name: Add specified repositories into sources list using specified filename
    apt_repository:
      repo: "{{ item.repo }}"
      state: present
      filename: "{{ item.file }}"
    loop:
      - { repo: 'deb https://download.sublimetext.com/apt/stable/', file: 'sublime' }
      - { repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main', file: 'google-chrome' }

  - name: Install packages
    apt:
      name: "{{ my_pkgs }}"
      state: present
      update_cache: yes
