- hosts: all
  become: yes
  tasks:
  - name : Install packages in loop
    apt: name={{item}} state=latest update_cache=true
    loop:
      - nano
      - net-tools
      - wireshark
      - unzip 
      - gtk2-engines-pixbuf 
      - gnome-icon-theme 
      - tango-icon-theme 
      - librsvg2-common
