- hosts: all
  tasks:
  - name : Install nano
    apt: name=nano state=latest update_cache=true
  - name : Install net-tools
    apt: name=net-tooks state=latest update_cache=true
  - name : Install wireshark
    apt: name=wireshark  state=latest update_cache=true
