- hosts: all
  become: yes  # Setze `become: yes` hier, um es für alle Tasks anzuwenden
  tasks:
    - name: Aktualisiere den APT-Paket-Cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Aktualisiert den Cache nur, wenn er älter als 1 Stunde ist

    - name: Installiere mehrere Pakete gleichzeitig
      apt:
        name:
          - wireshark-gtk
          - firefox-esr
          - wget
          - curl
          - dnsmasq
          - ncat
          - openvpn
          - unzip
          - whois
          - nmap
          - snapd
          - arping
          - dsniff
          - frr
          - iperf3
          - openvswitch-switch
          - traceroute
          - hping3
        state: latest

    - name: Clone a github repository for the exams
      git:
        repo: 'https://github.com/scimbe/rn-practice'
        dest: "/home/mininet/rn-practice"
        clone: yes
        update: yes
      become_user: mininet  # `become_user` sollte innerhalb des Tasks sein, falls nur für diesen Task angewendet        
