- name: Install Visual Studio Code on Debian (aarch64 or x86_64)
  hosts: all
  become: true
  vars:
    desktop_user: "mininet"

  tasks:
    - name: Show visual notification
      become_user: "{{ desktop_user }}"
      environment:
        DISPLAY: ":1"
      shell: |
        (
          xmessage -center "Ansible configuration in progress..." &
          echo $! > /tmp/notify.pid
        )
      async: 300
      poll: 0

    - name: Detect system architecture
      ansible.builtin.command: uname -m
      register: arch_output
      changed_when: false

    - name: Set download URL based on architecture
      ansible.builtin.set_fact:
        vscode_url: >-
          {{
            'https://update.code.visualstudio.com/latest/linux-deb-arm64/stable' 
            if arch_output.stdout == 'aarch64' 
            else 'https://update.code.visualstudio.com/latest/linux-deb-x64/stable'
          }}

    - name: Download Visual Studio Code package
      ansible.builtin.get_url:
        url: "{{ vscode_url }}"
        dest: "/tmp/vscode.deb"
      retries: 3
      delay: 10
      timeout: 600

    - name: Install Visual Studio Code
      ansible.builtin.apt:
        deb: "/tmp/vscode.deb"
      register: install_result
      retries: 3
      until: install_result is success

    - name: Ensure Visual Studio Code is installed
      ansible.builtin.command: code --version
      register: vscode_version
      changed_when: false

    - name: Display installed Visual Studio Code version
      ansible.builtin.debug:
        msg: "Installed Visual Studio Code version: {{ vscode_version.stdout_lines[0] }}"
      
    - name: Remove notification
      become_user: "{{ desktop_user }}"
      environment:
        DISPLAY: ":1"
      shell: |
        if [ -f /tmp/notify.pid ]; then
          kill $(cat /tmp/notify.pid) || true
          rm /tmp/notify.pid
        fi
      args:
        executable: /bin/bash
