---
- name: Xfce customizations
  hosts: localhost
  become: true
  vars:
    desktop_user: abc
    wallpaper:
      url: https://scimbe.de/wall/wallpaper-big.png
      path: /config/wallpaper-scimbe.png
    theme:
      repo: https://github.com/paullinuxthemer/PRO-Dark-XFCE-Edition/
      name: PRO-dark-XFCE-4.14
    gateway_ip: "{{ ansible_default_ipv4.gateway }}"
    ssh_port: "4040"
    # Standard Repo-Wahl ist '0', kann über Extra-Vars überschrieben werden
    repo_choice: "{{ repo_choice_var | default('0') }}"
    valid_repo_choices: ['0', 'VS_Pattern', 'VS_Script', 'Alles']

  tasks:
    # Neue Tasks hinzugefügt: Verzeichnis erstellen und JDK installieren
    - name: Create man directory
      file:
        path: /usr/share/man/man1
        state: directory
        mode: '0755'
        recurse: yes  # Stellt sicher, dass alle übergeordneten Verzeichnisse erstellt werden
      
    - name: Install default-jdk
      apt:
        name: default-jdk
        state: present
        update_cache: yes
        cache_valid_time: 3600  # Vermeidet unnötige Updates, wenn der Cache weniger als 1 Stunde alt ist
    
    # System aktualisieren
    - name: Update APT package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Cache ist für eine Stunde gültig
      
    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
  
    # Neue Tasks hinzugefügt: Verzeichnis erstellen und JDK installieren
    - name: Create man directory
      file:
        path: /usr/share/man/man1
        state: directory
        mode: '0755'
        recurse: yes  # Stellt sicher, dass alle übergeordneten Verzeichnisse erstellt werden
      
    - name: Install default-jdk
      apt:
        name: default-jdk
        state: present
      when: repo_choice == 'VS_Pattern' or repo_choice == 'Alles'
    
    - name: Show visual notification
      become_user: "{{ desktop_user }}"
      environment:
        DISPLAY: "{{ lookup('env', 'DISPLAY') }}"
      shell: |
        (
          xmessage -center "Ansible configuration in progress..." &
          echo $! > /tmp/notify.pid
        )
      async: 300
      poll: 0
      args:
        executable: /bin/bash
    
    - name: Ensure XFCE4 is running
      become_user: "{{ desktop_user }}"
      environment:
        DISPLAY: "{{ lookup('env', 'DISPLAY') }}"
        XAUTHORITY: "/home/{{ desktop_user }}/.Xauthority"
      shell: |
        pgrep xfce4-session || xfce4-session &
      async: 300
      poll: 0
      args:
        executable: /bin/bash
    
    - name: Wait for XFCE4 to start
      wait_for:
        timeout: 10
    
    - name: Configure desktop environment
      become_user: "{{ desktop_user }}"
      environment:
        DISPLAY: "{{ lookup('env', 'DISPLAY') }}"
        XAUTHORITY: "/home/{{ desktop_user }}/.Xauthority"
      block:
        - name: Download background
          get_url:
            url: "{{ wallpaper.url }}"
            dest: "{{ wallpaper.path }}"
            mode: '0666'
            force: no  # Überspringt den Download, wenn die Datei bereits existiert
    
        - name: Configure desktop icons
          xfconf:
            channel: xfce4-desktop
            property: "/desktop-icons/file-icons/show-{{ item }}"
            value_type: bool
            value: "false"
          loop:
            - removable
            - filesystem
            - home
    
        - name: Disable all desktop icons
          xfconf:
            channel: xfce4-desktop
            property: "/desktop-icons/style"
            value_type: int
            value: 0
            
        - name: Set wallpaper directly
          shell: |
            xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorVNC-0/workspace0/last-image -s "{{ wallpaper.path }}"
            xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorVNC-0/workspace1/last-image -s "{{ wallpaper.path }}"
            xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorVNC-0/workspace2/last-image -s "{{ wallpaper.path }}"
            xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorVNC-0/workspace3/last-image -s "{{ wallpaper.path }}"
          args:
            executable: /bin/bash
    
        - name: Kill existing xfdesktop process
          shell: killall xfdesktop || true
          ignore_errors: yes
    
        - name: Wait for process to end
          wait_for:
            timeout: 2
    
        - name: Start xfdesktop
          shell: xfdesktop &
          async: 300
          poll: 0
    
        - name: Start Conky
          shell: killall conky || true; nohup conky > /dev/null 2>&1 &
          args:
            chdir: "/"
            executable: /bin/bash
    
        - name: Setup theme
          block:
            - name: Clone theme repository
              git:
                repo: "{{ theme.repo }}"
                dest: /config/.themes
                clone: yes
                update: yes
    
            - name: Apply theme
              xfconf:
                channel: xsettings
                property: "/Net/ThemeName"
                value_type: string
                value: "{{ theme.name }}"
        
        - name: Remove notification
          shell: |
            if [ -f /tmp/notify.pid ]; then
              kill $(cat /tmp/notify.pid) || true
              rm /tmp/notify.pid
            fi
          args:
            executable: /bin/bash

# Importiere das VS-Playbook, wenn VS_Pattern ausgewählt ist
#- name: Import VS Playbook
#  import_playbook: ../vs/vs_pattern.yml

