- hosts: all
  tasks:
    - name: Install packages in loop
      become: yes
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: true
      loop:
        - python3-setuptools 
        - python3 
        - python3-pip
        - wireshark-gtk
        - firefox
        - wget 
        - curl
        
    - name: Clone a github repository for the exams
      git:
        repo: 'https://github.com/scimbe/rn-practice'
        dest: "{{ lookup('env','HOME') }}/rn-practice"
        clone: yes
        update: yes
