- hosts: all
  tasks:
    - name: Install packages in loop
      become: yes
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: true
      loop:
        - mininet

    - name: Clone a github repository for the exams
      git:
        repo: 'https://github.com/scimbe/rn-practice'
        dest: "{{ lookup('env','HOME') }}/rn-practice"
        clone: yes
        update: yes

    - name: Install the exam setup
      become: yes
      command: chdir="{{ lookup('env','HOME') }}/rn-practice" /bin/bash ./setup/mininet.sh
